# Generated by Django 3.2 on 2025-12-03 23:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BusType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=150)),
                ('passport', models.CharField(max_length=20, unique=True)),
                ('driver_class', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=1)),
                ('birth_date', models.DateField()),
                ('experience_years', models.PositiveIntegerField()),
                ('base_salary', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=10)),
                ('start_point', models.CharField(max_length=100)),
                ('end_point', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('interval_minutes', models.PositiveIntegerField()),
                ('duration_minutes', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reg_number', models.CharField(max_length=20, unique=True)),
                ('bus_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buses', to='core.bustype')),
            ],
        ),
        migrations.CreateModel(
            name='WorkShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('ON_LINE', 'Вышел на линию'), ('BROKEN', 'Не вышел: поломка'), ('NO_DRIVER', 'Не вышел: нет водителя'), ('OTHER', 'Не вышел: другая причина')], default='ON_LINE', max_length=10)),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.bus')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.driver')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='shifts', to='core.route')),
            ],
            options={
                'unique_together': {('date', 'bus', 'start_time')},
            },
        ),
    ]
